package com.escodro.designsystem

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF005fb1)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd3e3ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001c3b)
val md_theme_light_secondary = Color(0xFF555f71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd8e3f8)
val md_theme_light_onSecondaryContainer = Color(0xFF121c2b)
val md_theme_light_tertiary = Color(0xFF6e5676)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf7d8ff)
val md_theme_light_onTertiaryContainer = Color(0xFF271330)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfbff)
val md_theme_light_onBackground = Color(0xFF1b1b1d)
val md_theme_light_surface = Color(0xFFfdfbff)
val md_theme_light_onSurface = Color(0xFF1b1b1d)
val md_theme_light_surfaceVariant = Color(0xFFdfe2eb)
val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
val md_theme_light_outline = Color(0xFF74777f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f4)
val md_theme_light_inverseSurface = Color(0xFF2f3033)

val md_theme_dark_primary = Color(0xFFa4c8ff)
val md_theme_dark_onPrimary = Color(0xFF003060)
val md_theme_dark_primaryContainer = Color(0xFF004788)
val md_theme_dark_onPrimaryContainer = Color(0xFFd3e3ff)
val md_theme_dark_secondary = Color(0xFFbcc7dc)
val md_theme_dark_onSecondary = Color(0xFF273141)
val md_theme_dark_secondaryContainer = Color(0xFF3d4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFd8e3f8)
val md_theme_dark_tertiary = Color(0xFFdabde2)
val md_theme_dark_onTertiary = Color(0xFF3d2846)
val md_theme_dark_tertiaryContainer = Color(0xFF553f5d)
val md_theme_dark_onTertiaryContainer = Color(0xFFf7d8ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1d)
val md_theme_dark_onBackground = Color(0xFFe3e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1d)
val md_theme_dark_onSurface = Color(0xFFe3e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF43474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c6cf)
val md_theme_dark_outline = Color(0xFF8e919a)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1d)
val md_theme_dark_inverseSurface = Color(0xFFe3e2e6)

val seed = Color(0xFF1976d2)
val error = Color(0xFFba1b1b)
